/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package streams;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.jupiter.api.Assertions.*;

class Tests {
    @Test
    void testExample() {
        // Set up for putput redirect
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outContent));

        // Set up and run main
        Main myMain = new Main();
        myMain.main(null);

        // Restore output
        System.setOut(originalOut);

        // Build array of output line strings
        String[] outputLines = outContent.toString().split("\n");

        // Expected output
        String[] expected = {
                "Number of products: 5",
                "Total price: 4.95",
                "---=== Distinct Products ===---",
                "Almond Joy",
                "Reeses",
                "Snickers"
        };

        assertArrayEquals(expected, outputLines);
    }

}