/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package streams;

import java.util.ArrayList;
import java.util.stream.Stream;

public class Main {
    public static void main(String[] args) {

        // Read in the input file
        XmlReader myXmlReader = new XmlReader("products.xml");

        // Get the ArrayList from the XmlReader

        // Use Streams to generate the report



    }
}
